name: moostrapScrollspy
description: port of twitter bootstrap-scrollspy into mootools
author: D_mitar
category: Interface
tags: [bootstrap,twitter,scrollspy]
demo: http://jsfiddle.net/dimitar/mc9yc/
current: 1.0